services:
  api:
    container_name: library-api
    image: api-image
    build: .
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      mongo:
        condition: service_healthy
  
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping').ok", "--quiet"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  mongo-data: